import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Hero from "../components/hero";
import Link from "next/link";
import classes from './shacks/shacks.module.css';
import { PrismaClient } from "@prisma/client";
import ShackCard from '../components/shackcard/ShackCard'
import Button from '@mui/material/Button';


const prisma = new PrismaClient();

export default function Home(props) {
  const shacks = props.shacks;

  return (
    <div className={styles.container}>
      <Head>
        <title>Cabannes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Hero />
        <Link href="/signup">
          <a>Inscription</a>
        </Link>
          <div className={classes.cards}>
          {shacks?.map((shack, i) => (
            <ShackCard shack={shack} key={i} />
          ))}
        </div>
        <div>
          <Button variant="outlined" size="large" href="/shacks" >
            Voir toutes les cabannes
          </Button>
        </div>


      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const allShacks = await prisma.cabane.findMany();
  return {
    props: {
      shacks: allShacks,
    },
  };
}

