import Head from "next/head";
import styles from "../styles/Home.module.css";
import Hero from "../components/hero";
import ShackCard from "../components/shackcard/ShackCard";
import Button from "@mui/material/Button";
import prisma from "../lib/prisma.ts";

export default function Home(props) {
  const shacks = props.shacks;

  return (
    <div>
      <Head>
        <title>Cabanne.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Hero />
        <div className={styles.cards}>
          <div className="my-4 py-1 text-center">
            <div className="mx-auto">
              <span className="fs-3 fw-bold mb-4">
                Trouvez la bicoque de vos rêves !
              </span>
            </div>
          </div>
          <div className={styles.cards}>
            {shacks?.map((shack, i) => (
              <ShackCard width="30%" shack={shack} key={i} />
            ))}
          </div>
          <div className={styles.bottomBtn}>
            <a href="/shacks" className="btn btn-outline-secondary">
              Nos Cabanes
            </a>
          </div>
        </div>
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const allShacks = await prisma.cabane.findMany({
    take: 6,
    orderBy: [
      {
        title: "asc",
      },
    ],
  });
  return {
    props: {
      shacks: allShacks,
    },
  };
}
